### ISSUE TITLE
[help] Unable to upload a file to my instance

### ISSUE THREAD

**Issue by RisedSky** [HiberFile/HiberFile#52]
Hello, I can't upload a file to my instance, any ideas?
I followed the readme steps, but it seems that I have to configure something extra
![image](https://user-images.githubusercontent.com/23197999/136868414-21a9b4a1-741b-4056-90dc-70bf3ce8ceaf.png)

If you can help me, that would be nice :)

**Comment by RisedSky** [comment]
Here is my console, I do not know if it can help you

![image](https://user-images.githubusercontent.com/23197999/136868477-a3a424fb-1a27-461e-b79c-6cfb2847d15f.png)

**Comment by arthur-fontaine** [comment]
Your console says "WARN No `.env` file found in /root/hiberfile". Check that you have a .env file with a HIBERAPI_URL property.

PS: Sorry for the delay, we did not receive the notification from GitHub...

**Comment by RisedSky** [comment]
Hello, there is no .env or .env exemple on the GitHub, or maybe I didn't see it ?

Can you do a commit of a .env.exemple so I can copy it ?

Also, can we configure if it's E2E ?
 I don't want to have it and want to disable it bcs it can take a lot of CPU

**Comment by arthur-fontaine** [comment]
E2E is "end to end" right? What do you call "end to end" here?

**Comment by RisedSky** [comment]
> E2E is "end to end" right? What do you call "end to end" here?

I mean, Lufi is doing E2E, when it's sent to the server, it's encrypted, but when downloading the file, it's uncrypted to the downloading user.
That's what i'm calling E2E

**Comment by arthur-fontaine** [comment]
Hiberfile does not encrypt file client-side because of RAM lack. Client-side, the only encryption is the SSL. So Hiberfile does not use E2E encryption. Does that answer your question?

**Comment by arthur-fontaine** [comment]
f**k... I made a mistake in the issue associated with the commit...

**Comment by RisedSky** [comment]
> Hiberfile does not encrypt file client-side because of RAM lack. Client-side, the only encryption is the SSL. So Hiberfile does not use E2E encryption. Does that answer your question?

Yep ! :D
